### PR TITLE
use current update-notifier API

### LINKED ISSUE #21: update-notifier throwing error
```
Running "robotstxt:development" (robotstxt) task
Warning: pkg.name and pkg.version required Use --force to continue.
Error: pkg.name and pkg.version required
    at new UpdateNotifier (/Users/charlesrudolph/github/commercial-search/node_modules/grunt-robots-txt/node_modules/update-notifier/index.js:24:9)
    at module.exports (/Users/charlesrudolph/github/commercial-search/node_modules/grunt-robots-txt/node_modules/update-notifier/index.js:108:23)
    at Object.<anonymous> (/Users/charlesrudolph/github/commercial-search/node_modules/grunt-robots-txt/tasks/robotstxt.js:20:14)
```

Looking at its docs, the API being used is very outdated.

### PR DESCRIPTION
**Pull request by charlierudolph**
@t1st3 

resolves #21

### CODE REVIEW

**Comment by t1st3** [comment]
Thanks @charlierudolph

**Comment by charlierudolph** [comment]
Thanks. Any idea when the next release will be?

**Comment by t1st3** [comment]
I will bump tonight or tomorrow

**Comment by t1st3** [comment]
@charlierudolph, I just bumped to 0.3.5 a few minutes ago. Thanks again

**Pull request merged**
